#!/usr/bin/env bash
# This script displays information about subdomains of a domain

domain="$1"
subdomain="$2"

if [ -z "$subdomain" ]; then
    subdomain_list=("www" "lb-01" "web-01" "web-02")
else
    subdomain_list=("$subdomain")
fi

for sub in "${subdomain_list[@]}"; do
    record=$(dig +short "$sub.$domain")
    record_type=$(dig +short "$sub.$domain" | awk 'NR==1{print $4}')
    echo "The subdomain $sub is a $record_type record and points to $record"
done
